INSERT INTO product (name, waste_type) VALUES ('Novine', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Bilježnica', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Prospekt', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Katalog', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Knjiga', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Imenik', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Slikovnica', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Papir', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Pismo', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Papirnata vrećica', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Mapa', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Fascikl', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Kartonska kutija', 'PAPER');
INSERT INTO product (name, waste_type) VALUES ('Staklena boca', 'GLASS');
INSERT INTO product (name, waste_type) VALUES ('Staklenka', 'GLASS');
INSERT INTO product (name, waste_type) VALUES ('PE-HD', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('PE-LD', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('PET', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('PP', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('EPS', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Tetrapak', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('PVC', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('PS', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Flaša', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastična boca', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Izolacija kablova', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastična kašeta', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastična posuda', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastična vaza', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastična tegla', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Plastični podmetač', 'PLASTIC');
INSERT INTO product (name, waste_type) VALUES ('Trenirka', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Majica', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Pulover', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Dolčevita', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Gaće', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Čarape', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Podkošulja', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Košulja', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Jastučnica', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Odjeća', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Ručnik', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Posteljina', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Zavjesa', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Šešir', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Kapa', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Torba', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Krpena igračka', 'CLOTHES');
INSERT INTO product (name, waste_type) VALUES ('Kora voća', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Kora povrća', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Ljuska jaja', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Talog od kave', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Vrećica od čaja', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Ostatci kruha', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Ostatci voća', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Ostatci povrća', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Listovi povrća', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Uvenulo cvijeće', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Otpalo lišće', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Otkos trave', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Kora drveta', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Kosa', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Dlaka', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Piljevina', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Papirnata maramica', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Borova iglica', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Zemlja iz lončanica', 'ORGANIC');
INSERT INTO product (name, waste_type) VALUES ('Televizor', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Monitor', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Printer', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Skener', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Tipkovnica', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Miš', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kablovi', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Sat', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Lampa', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Elektronička pločica', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Svjetiljka', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kalkulator', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Mobitel', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Telefon', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kamera', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Radio', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('DVD player', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('CD player', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('MP3', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('MP4', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Tablet', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Toster', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Mikrovalna pečnica', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Mikroskop', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kalorimetar', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Glačalo', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Sušilo za kosu', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Hladnjak', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Perilica posuđa', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Perilica rublja', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Klima uređaj', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Ventilator', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Daljinski upravljač', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Termostat', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Pojačalo', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Bušilica', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Mašina za šivanje', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kuhalo za kavu', 'E_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Konzerva', 'METAL');
INSERT INTO product (name, waste_type) VALUES ('Limenka pića', 'METAL');
INSERT INTO product (name, waste_type) VALUES ('Aluminij', 'METAL');
INSERT INTO product (name, waste_type) VALUES ('Željezo', 'METAL');
INSERT INTO product (name, waste_type) VALUES ('Bakar', 'METAL');
INSERT INTO product (name, waste_type) VALUES ('AAA baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('AA baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('AAAA baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('A baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('B baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('C baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('D baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('F baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('N baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('A23 baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('A27 baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('BA5800 baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('Duplex baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('4SR44 baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('4.5-volt baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('9-volt baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('6-volt baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('J baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('Li-Ion baterija', 'BATTERIES');
INSERT INTO product (name, waste_type) VALUES ('Žarulja sa žarnom niti', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('Halogena žarulja', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('LED žarulja', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('Flouroscentna žarulja', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('Kompaktna flouroscentna žarulja', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('Žarulja visokog intenziteta pražnjenja', 'LIGHT_BULBS');
INSERT INTO product (name, waste_type) VALUES ('Meso', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kruh', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Kolač', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Torta', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Jaje', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Tjestenina', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Riža', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Povrće', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Voće', 'MIXED_WASTE');
INSERT INTO product (name, waste_type) VALUES ('Žitarice', 'MIXED_WASTE');